index/urls.py
# urls of app sorting_algorithm

from django.urls import path
from index import views

app_name = 'index'

urlpatterns = [
    # initial page
    path('', views.homepage, name='home'),
    
]








sorting_algorithm/urls.py
# urls of app sorting_algorithm

from django.urls import path
from sorting_algorithm import views

app_name = 'sorting_algorithm'

urlpatterns = [
    # initial page
    path('bubble_sorting/',views.bubble_sorting_algorithm,name='bubble_sorting'),
    path('selection_sorting/',views.selection_sorting_algorithm,name='selection_sorting'),
    path('insertion_sorting/',views.insertion_sorting_algorithm,name='insertion_sorting'),

]








sorting_algorithm_animation_project/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

# media
from django.conf import settings
from django.conf.urls.static import static

# app sorting_algorithm
from index import views

urlpatterns = [

    # sorting_algorithm
    path('',views.homepage,name='home'),

    # The above maps any URLs starting with rango/ to be handled by rango.
    path('sorting_algorithm/',include('sorting_algorithm.urls')),
    path('sorting_algorithm_performance/',include('sorting_algorithm_performance.urls')),
    path('index/',include('index.urls')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sorting_algorithm_performance/urls.py
# urls of app sorting_algorithm

from django.urls import path
from sorting_algorithm_performance import views

app_name = 'sorting_algorithm_performance'

urlpatterns = [
    path('', views.AlgorithmPerformance, name='algorithm_performance'),
    
]








index/models.py
from django.db import models

# Create your models here.

sorting_algorithm/models.py
from django.db import models

# Create your models here.

sorting_algorithm_performance/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def homepage(request):

    context_dict = {'boldmessage': 'Hello, this is home page!'}
    return render(request, 'index/home.html',context=context_dict)

sorting_algorithm/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def bubble_sorting_algorithm(request):

    context_dict = {'boldmessage': 'Hello, this is bubble!'}
    return render(request, 'sorting_algorithm/bubble_sorting.html',context=context_dict)

def selection_sorting_algorithm(request):

    context_dict = {'boldmessage': 'Hello, this is selection!'}
    return render(request, 'sorting_algorithm/selection_sorting.html',context=context_dict)

def insertion_sorting_algorithm(request):

    context_dict = {'boldmessage': 'Hello, this is insertion!'}
    return render(request, 'sorting_algorithm/insertion_sorting.html',context=context_dict)






sorting_algorithm_performance/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def AlgorithmPerformance(request):
    context_dict = {'boldmessage': 'Hello, this is algorithm performance!'}
    return render(request, 'sorting_algorithm_performance/algorithm_performance.html',context=context_dict)



templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
        <title>
            
            {% block title_block %}
            Project - Hello, world!
            {% endblock %}
        </title>
        
        {% block css_block %}
            <!-- This is css_block's default content. -->
        {% endblock %}

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

        <!-- CSS for animating -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/common_UI.css' %}">

    </head>

    <body>
        <!-- menu-->
        <!-- deal with hiden nav bar -->
        <div style='visibility:hidden;'>
            <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Test</a>
                  </div>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><strong>Home</strong></a></li>
                    <li><a href="#"><strong>Sorting Algorithm</strong></a></li>
                    <li><a href="#"><strong>Algorithm Perfromance</strong></a></li>
                  </ul>
            </div>
            </nav>
        </div> 

        {% block navigation %}
            <!-- This is navigation's default content. -->
        {% endblock %}

        <div class="container" id='workplace'>
            {% block workplace %}
                <!-- This is workplace's default content. -->
            {% endblock %}

            <div class="page-header" id="footer"> 
                <small>Copyright &copy; 2022 Sorting Algorithm Animation. All Rights Reserved.</small>
                <address>
                    Designed and built by <a href="mailto:2554563H@student.gla.ac.uk">Pai Huang</a>.
                </address>
            </div>
        </div>

        <!-- javascript -->

        {% block js_block %}
                <!-- This is js_block's default content. -->
        {% endblock %}
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <script type="text/javascript" src="{% static 'js/common_function.js' %}"></script>
    
    </body>
</html>

templates/base_animation.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}
    Ainmation of
    {% block algorithm_name %}
    {% endblock %}
{% endblock %}

{% block css_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/common_function.css' %}">
{% endblock %}

{% block navigation %}
<nav class="navbar navbar-default" data-spy="affix">

    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#top"><strong>Sorting Algorithm Animation</strong></a>
          </div>

          <!-- https://www.w3schools.com/bootstrap/bootstrap_glyphicons.asp -->
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'index:home' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                  <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                </svg>
                <strong>Home</strong></a></li>
            <li class="dropdown active"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-code" viewBox="0 0 16 16">
                  <path d="M5.854 4.854a.5.5 0 1 0-.708-.708l-3.5 3.5a.5.5 0 0 0 0 .708l3.5 3.5a.5.5 0 0 0 .708-.708L2.707 8l3.147-3.146zm4.292 0a.5.5 0 0 1 .708-.708l3.5 3.5a.5.5 0 0 1 0 .708l-3.5 3.5a.5.5 0 0 1-.708-.708L13.293 8l-3.147-3.146z"/>
                </svg>
                <strong>Sorting Algorithm</strong>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'sorting_algorithm:bubble_sorting' %}">Bubble</a></li>
                  <li><a href="{% url 'sorting_algorithm:insertion_sorting' %}">Insertion</a></li>
                  <li><a href="{% url 'sorting_algorithm:selection_sorting' %}">Selection</a></li>
                </ul>
              </li>
            <li><a href="{% url 'sorting_algorithm_performance:algorithm_performance' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
                  <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
                  <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
                </svg>
                <strong>Algorithm Perfromance</strong></a></li>
          </ul>
    </div>
</nav>
{% endblock %}

{% block workplace %}
<div class="row">
    <div class="jumbotron">
        <!-- jumbotron page-header-->
        {% block page_header %}
        {% endblock %}
   </div>
</div>

<div class="row">
    <!-- speed -->
    <div class="col-sm-12 col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">

                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-1-circle" viewBox="0 0 16 16">
                    <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM9.283 4.002V12H7.971V5.338h-.065L6.072 6.656V5.385l1.899-1.383h1.312Z"/>
                </svg>
                <strong>Speed Control</strong>

            </div>
            <div class="panel-body">
                <!-- demo control -->
                <br>
                <strong>Speed of animation:  </strong>
                <br>
                <br>
                <input type="range" id="speed" min="1" max="15" value="5" oninput="displaySpeed()" onchange="displaySpeed()">
                <br>
                <strong><span id="display_speed">x 1</span></strong>
                <br>
                <br>
                <p class="text-danger">Tip: Please setting speed before playing animation.</p>
            </div>
          </div>
    </div>

    <!-- initial conditions -->
    <div class="col-sm-12 col-md-8">
        <div class="panel panel-warning">
            <div class="panel-heading">
                
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-2-circle" viewBox="0 0 16 16">
                    <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM6.646 6.24v.07H5.375v-.064c0-1.213.879-2.402 2.637-2.402 1.582 0 2.613.949 2.613 2.215 0 1.002-.6 1.667-1.287 2.43l-.096.107-1.974 2.22v.077h3.498V12H5.422v-.832l2.97-3.293c.434-.475.903-1.008.903-1.705 0-.744-.557-1.236-1.313-1.236-.843 0-1.336.615-1.336 1.306Z"/>
                  </svg>
                  <strong>Setting Initial Condition and Play</strong></div>
            <div class="panel-body">
                <div class="row">
                    <form class="form-inline" action="/action_page.php">
                        <div class="form-group has-warning">
                            <label>There are </label>
                            <input type="number" class="form-control" placeholder="Enter positive integer" id="n_bars" min="3" value="10"
                            data-toggle="tooltip" data-placement="top" title="Please enter positive integer!"
                                   onkeydown="if(event.keyCode==13){alert('Please click the button to submit!');return false;}">
                            <label> Bars in the Animation.</label>
                        </div>
                    </form>
                </div>

                <div class="row btn-group">
                    <button type="button" class="btn btn-primary" onclick="RandomDemo()">Random</button>
                    <button type="button" class="btn btn-success" onclick="NearlyDemo()">Nearly Sorted</button>
                    <button type="button" class="btn btn-warning" onclick="ReversedDemo()">Reversed Sorted</button>
                    <button type="button" class="btn btn-danger" onclick="UniqueDemo()">Few Unique</button>
                </div>

                <hr>
                <div class="row">
                    <!-- user input -->
                    <form class="form-inline" action="/action_page.php">
                        <div class="form-group has-warning">
                            <label>User Input:  </label>
                            <input type="text" class="form-control" placeholder="Enter number array" id="user_input" value="1,55,75,83,-33,94,2,49,-40,28,42,20,37,68,99"
                            data-toggle="tooltip" data-placement="top" title="Please enter an array of numbers separated by commas(,), and the number in [-100, 100]!"
                                   onkeydown="if(event.keyCode==13){alert('Please click the button to submit!');return false;}">
                            <button type="button" class="btn btn-info" onclick="UserInputDemo()">User Play</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- Pseudo-code -->
    <div class="col-sm-12 col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading"><strong>Pseudo-code of Sorting Algorithm</strong></div>
            <div class="panel-body" id="algorithm_code">
                {% block algorithm_code %}
                {% endblock %}
            </div>
          </div>
    </div>

    <!-- animation -->
    <div class="col-sm-12 col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading"><strong>Animation of Sorting Algorithm</strong></div>
            <div class="panel-body" id="algorithm_demo_frame">
                <div class="row">
                    
                    {% block algorithm_legend %}
                    {% endblock %}
                </div>
                <div class="row" id="algorithm_demo">

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_block %}
<script type="text/javascript" src="{% static 'js/common_animation.js' %}"></script>

    {% block js_algorithm %}
    {% endblock %}
{% endblock %}

templates/index/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block css_block %}
{% endblock %}

{% block navigation %}
<nav class="navbar navbar-default" data-spy="affix">

    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#top"><strong>Sorting Algorithm Animation</strong></a>
          </div>

          <!-- https://www.w3schools.com/bootstrap/bootstrap_glyphicons.asp -->
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'index:home' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                  <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                </svg>
                <strong>Home</strong></a></li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-code" viewBox="0 0 16 16">
                  <path d="M5.854 4.854a.5.5 0 1 0-.708-.708l-3.5 3.5a.5.5 0 0 0 0 .708l3.5 3.5a.5.5 0 0 0 .708-.708L2.707 8l3.147-3.146zm4.292 0a.5.5 0 0 1 .708-.708l3.5 3.5a.5.5 0 0 1 0 .708l-3.5 3.5a.5.5 0 0 1-.708-.708L13.293 8l-3.147-3.146z"/>
                </svg>
                <strong>Sorting Algorithm</strong>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'sorting_algorithm:bubble_sorting' %}">Bubble</a></li>
                  <li><a href="{% url 'sorting_algorithm:insertion_sorting' %}">Insertion</a></li>
                  <li><a href="{% url 'sorting_algorithm:selection_sorting' %}">Selection</a></li>
                </ul>
              </li>
            <li><a href="{% url 'sorting_algorithm_performance:algorithm_performance' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
                  <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
                  <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
                </svg>
                <strong>Algorithm Perfromance</strong></a></li>
          </ul>
    </div>
</nav>
{% endblock %}

{% block workplace %}
    <!-- <h1>Index says...this is home page</h1> -->

    <div class="row">
        <div class="jumbotron" id="index">
            <!-- jumbotron page-header-->
            <h1>Wellcome to <br>Sorting Algorithm Animation!</h1>
            <blockquote>
                <p>
                    This is a web application to help beginner programmers understand the basics of sorting algorithms by animating sorting algorithms and comparing the performance of these algorithms.
                    
                </p>
            </blockquote>

            <div id="index_menu">
                <div class="row">
                    <div class="col-sm-12 col-md-8">
                        <br>
                        <p>
                            Explaining the animation of sorting algorithms with the steps of the pseudocode.
                        </p>
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <a href="{% url 'sorting_algorithm:bubble_sorting' %}">
                            <button class="index_button"><strong><span>Animation </span></strong></button>
                        </a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-md-8">
                        <br>
                        <p>
                            Comparing the performance of sorting algorithms by average running time.
                        </p>
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <a href="{% url 'sorting_algorithm_performance:algorithm_performance' %}">
                            <button class="index_button"><strong><span>Performance </span></strong></button>
                        </a>
                    </div>
                </div>
            </div>

       </div>
    </div>
    
    <div class="row">
        <div class="panel panel-danger">
            <div class="panel-heading">Related Resource Links</div>
            <div class="panel-body" id="related_links">
                <a href="https://www.geeksforgeeks.org/sorting-algorithms/?ref=lbp">Introduction of Sorting Algorithm [Sample 1]</a><br>
                <a href="https://www.tutorialspoint.com/data_structures_algorithms/sorting_algorithms.htm">Introduction of Sorting Algorithm [Sample 2]</a><br>
                <a href="https://visualgo.net/en/sorting?slide=1">Animation of Sorting Algorithm [Sample 1]</a><br>
                <a href="https://www.sortvisualizer.com/">Animation of Sorting Algorithm [Sample 2]</a><br>
                <a href="https://www.toptal.com/developers/sorting-algorithms">Comparative Performance of Sorting Algorithm [Sample 1]</a><br>
                <a href="https://math.hws.edu/eck/js/sorting/xSortLab.html">Comparative performance of Sorting Algorithm [Sample 2]</a><br>
                <a href="https://caspervonb.xyz/toneofsorting/">Fun of Sorting Algorithm with music [Sample 1]</a><br>
            </div>
        </div>
    </div>

    <!-- <div><img src="{% static 'images/login_background.jpg'%}" alt="University" width="600"/></div> -->
{% endblock %}

{% block js_block %}
{% endblock %}


templates/sorting_algorithm/bubble_sorting.html
{% extends 'base_animation.html' %}
{% load staticfiles %}

{% block algorithm_name %}
    Bubble Sort
{% endblock %}

{% block page_header %}
<h1>Bubble Sorting Algorithm!</h1>
<blockquote class="blockquote-reverse">
    <p>
        Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in the wrong order.
    </p>
    <p>
        This algorithm is not suitable for large data sets as its average and worst-case time complexity is quite high.
    </p>
    <small>This information is from <cite title="Source Title"><a href="https://www.geeksforgeeks.org/bubble-sort/">GeeksforGeeks</a></cite></small>
</blockquote>
{% endblock %}

{% block algorithm_code %}
<pre><p id="code_part_0">procedure bubbleSort(list : array of items)</p><p id="code_part_1">    loop = list.count;</p><p id="code_part_2">    for i = 0 to loop-1 do:<br>    swapped = false</p><p id="code_part_3">        for j = 0 to loop-1 do:</p><p id="code_part_4">        /* compare the adjacent elements */<br>            if list[j] > list[j+1] then</p><p id="code_part_5">                /* swap them */<br>                swap( list[j], list[j+1] )<br>                swapped = true</p><p id="code_part_6">            end if<br>        end for</p><p id="code_part_7">    /*if no number was swapped that means<br>    array is sorted now, break the loop.*/<br>        if(not swapped) then<br>            break<br>        end if</p><p id="code_part_8">    end for</p><p id="code_part_9">end procedure return list</p>
</pre>   
<blockquote class="blockquote-reverse">
    <small>This information is from <cite title="Source Title"><a href="https://www.tutorialspoint.com/data_structures_algorithms/bubble_sort_algorithm.htm">TutorialsPoint</a></cite></small>
</blockquote>

<!-- procedure bubbleSort( list : array of items )
        loop = list.count;
        for i = 0 to loop-1 do:
            swapped = false
            for j = 0 to loop-1 do:
                /* compare the adjacent elements */   
                if list[j] > list[j+1] then
                    /* swap them */
                    swap( list[j], list[j+1] )		 
                    swapped = true
                end if
            end for
            /*if no number was swapped that means 
            array is sorted now, break the loop.*/
            if(not swapped) then
                break
            end if
        end for                    
    end procedure return list -->
{% endblock %}

{% block algorithm_legend %}
<div class="col-sm-12 col-md-4">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16"  style="background-color: #adb5bd;">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
      </svg> Waiting
    
</div>
<div class="col-sm-12 col-md-4">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16"  style="background-color: #0dcaf0;">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
      </svg> Active
</div>
<div class="col-sm-12 col-md-4">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16"  style="background-color: #dc3545;">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
      </svg> Sorted
</div>
{% endblock %}

{% block js_algorithm %}
<script type="text/javascript" src="{% static 'js/bubble_sort.js' %}"></script>
{% endblock %}

templates/structure.html
<!-- base.html -->
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block css_block %}
{% endblock %}

{% block navigation %}
{% endblock %}

{% block workplace %}
{% endblock %}

{% block js_block %}
{% endblock %}


<!-- <li><a href="{% url 'index:home' %}">Home</a></li>
<li><a href="{% url 'sorting_algorithm:bubble_sorting' %}">Bubble</a></li>
<li><a href="{% url 'sorting_algorithm:insertion_sorting' %}">Insertion</a></li>
<li><a href="{% url 'sorting_algorithm:selection_sorting' %}">Selection</a></li>
<li><a href="{% url 'sorting_algorithm_performance:algorithm_performance' %}">Performance</a></li> -->


<!-- base_animation.html -->
{% block algorithm_name %}
{% endblock %}

{% block page_header %}
{% endblock %}

{% block algorithm_code %}
{% endblock %}

{% block algorithm_legend %}
{% endblock %}

{% block js_algorithm %}
{% endblock %}